name: deepseenet3.6
channels:
  - anaconda
  - conda-forge
  - auto
dependencies:
  - python=3.6
  - docutils=0.13.1
  - docopt=0.6.2
  - pytest=3.1.3
  - tqdm=4.19.9
  - numpy=1.14.2
  - keras=2.1.5
  - scikit-learn=0.19.1
  - pip:
    - GPUtil==1.2.3
    - opencv-python
